name: tekartik_browser_utils
version: 0.6.9
description: Browser utils
author: Alexandre Roux <alex@tekartik.com>
homepage: https://github.com/tekartik/browser_utils.dart
environment:
  sdk: '>=2.4.0 <3.0.0'
dependencies:
  synchronized: any
  js: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.3+2'
  stack_trace:
dev_dependencies:
  process_run: '>=0.10.0+1'
  dev_test: any
  test: '>=1.2.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.0'
  build_runner: '>=1.7.0'
  build_test: '>=0.10.8'
  build_web_compilers: '>=1.2.2'
